<?php
session_start();
// Allow both admin and employee
if (!isset($_SESSION['logged_in']) || ($_SESSION['role'] !== 'employee' && $_SESSION['role'] !== 'admin')) {
    header("Location: login.php");
    exit();
}

require_once 'config/database.php';
$user_id = $_SESSION['user_id'];
$role = $_SESSION['role'];

$database = new Database();
$db = $database->getConnection();

// Get current week sales
if ($role === 'admin') {
    // Admin sees all sales for the week
    $query = "SELECT s.*, u.full_name as seller_name 
              FROM sales s 
              LEFT JOIN users u ON s.sold_by = u.user_id
              WHERE YEARWEEK(s.sale_date, 1) = YEARWEEK(CURDATE(), 1)
              ORDER BY s.sale_date DESC";
    $stmt = $db->prepare($query);
    $stmt->execute();
} else {
    // Employee sees only their sales
    $query = "SELECT s.*, :full_name as seller_name 
              FROM sales s 
              WHERE YEARWEEK(s.sale_date, 1) = YEARWEEK(CURDATE(), 1) AND s.sold_by = :user_id
              ORDER BY s.sale_date DESC";
    $stmt = $db->prepare($query);
    $stmt->bindParam(':user_id', $user_id);
    $stmt->bindValue(':full_name', $_SESSION['full_name']);
    $stmt->execute();
}

$week_sales = $stmt->fetchAll();

// Calculate Summaries
$payment_summary = [];
$daily_summary = [];
$total_revenue = 0;

foreach ($week_sales as $sale) {
    // Payment Summary
    $method = ucfirst($sale['payment_method']);
    if (!isset($payment_summary[$method])) {
        $payment_summary[$method] = 0;
    }
    $payment_summary[$method] += $sale['sale_price'];
    
    // Daily Summary
    $day = date('l, M d', strtotime($sale['sale_date']));
    if (!isset($daily_summary[$day])) {
        $daily_summary[$day] = ['count' => 0, 'total' => 0];
    }
    $daily_summary[$day]['count']++;
    $daily_summary[$day]['total'] += $sale['sale_price'];
    
    $total_revenue += $sale['sale_price'];
}

// Sort daily summary by date (it's populated in reverse order from sales, so let's reverse it to be chronological or just keep it)
// Sales are DESC, so daily summary will be populated starting from latest date.
// If we want chronological order for the table:
$daily_summary = array_reverse($daily_summary);

?>
<!DOCTYPE html>
<html>
<head>
    <title>Weekly Sales Report</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        h1 { margin: 0; color: #333; }
        .meta-info { margin: 5px 0; color: #555; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        
        .total-row td { border-top: 2px solid #333; font-weight: bold; }
        .amount { text-align: right; }
        
        .section-title { font-size: 1.1em; font-weight: bold; margin-top: 20px; margin-bottom: 10px; color: #444; border-left: 4px solid #007bff; padding-left: 10px; }
        
        .summary-wrapper { display: flex; gap: 20px; }
        .summary-col { flex: 1; }
        
        @media print {
            body { padding: 0; }
            .no-print { display: none; }
            th { background-color: #eee !important; -webkit-print-color-adjust: exact; }
            .summary-wrapper { break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center;">
        <a href="<?php echo $role === 'admin' ? 'admin.php' : 'employee.php'; ?>" style="padding: 10px 20px; background-color: #6c757d; color: white; text-decoration: none; border-radius: 4px;">&larr; Back to Dashboard</a>
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer; background-color: #007bff; color: white; border: none; border-radius: 4px;">Print Report</button>
    </div>

    <div class="header">
        <h1>Weekly Sales Report</h1>
        <p class="meta-info">Week of: <?php echo date('M d', strtotime('monday this week')) . ' - ' . date('M d, Y', strtotime('sunday this week')); ?></p>
        <p class="meta-info">Generated By: <?php echo htmlspecialchars($_SESSION['full_name']); ?> (<?php echo ucfirst($role); ?>)</p>
    </div>
    
    <div class="summary-wrapper">
        <div class="summary-col">
            <h3 class="section-title">Daily Breakdown</h3>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th style="text-align: center;">Sales Count</th>
                        <th class="amount">Revenue</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($daily_summary as $day => $data): ?>
                    <tr>
                        <td><?php echo $day; ?></td>
                        <td style="text-align: center;"><?php echo $data['count']; ?></td>
                        <td class="amount">XAF <?php echo number_format($data['total'], 0); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        
        <div class="summary-col">
            <h3 class="section-title">Payment Summary</h3>
            <table>
                <thead>
                    <tr>
                        <th>Method</th>
                        <th class="amount">Total</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($payment_summary as $method => $amount): ?>
                    <tr>
                        <td><?php echo $method; ?></td>
                        <td class="amount">XAF <?php echo number_format($amount, 0); ?></td>
                    </tr>
                    <?php endforeach; ?>
                    <tr class="total-row">
                        <td>Total Week Revenue</td>
                        <td class="amount">XAF <?php echo number_format($total_revenue, 0); ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    
    <h3 class="section-title">Detailed Sales Log</h3>
    <table>
        <thead>
            <tr>
                <th>Date/Time</th>
                <th>Item</th>
                <th>Type</th>
                <th>Method</th>
                <?php if ($role === 'admin'): ?>
                <th>Seller</th>
                <?php endif; ?>
                <th class="amount">Price</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($week_sales) > 0): ?>
                <?php foreach($week_sales as $sale): ?>
                <tr>
                    <td><?php echo date('M d, H:i', strtotime($sale['sale_date'])); ?></td>
                    <td>
                        <?php echo "Item #" . $sale['item_id']; ?>
                        <br><small style="color: #666;"><?php echo htmlspecialchars($sale['notes']); ?></small>
                    </td>
                    <td><?php echo ucfirst($sale['item_type']); ?></td>
                    <td><?php echo ucfirst($sale['payment_method']); ?></td>
                    <?php if ($role === 'admin'): ?>
                    <td><?php echo htmlspecialchars($sale['seller_name']); ?></td>
                    <?php endif; ?>
                    <td class="amount">XAF <?php echo number_format($sale['sale_price'], 0); ?></td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="<?php echo ($role === 'admin') ? 6 : 5; ?>" style="text-align: center; padding: 20px;">No sales found for this week.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

</body>
</html>
