<?php
require_once 'includes/session.php';
// Allow both admin and employee
if (!isset($_SESSION['logged_in']) || ($_SESSION['role'] !== 'employee' && $_SESSION['role'] !== 'admin')) {
    header("Location: login.php");
    exit();
}

require_once 'config/database.php';
$user_id = $_SESSION['user_id'];
$role = $_SESSION['role'];

$database = new Database();
$db = $database->getConnection();

// Get today's data
if ($role === 'admin') {
    // Admin sees all sales for today
    $query = "SELECT s.*, u.full_name as seller_name 
              FROM sales s 
              LEFT JOIN users u ON s.sold_by = u.user_id
              WHERE DATE(s.sale_date) = CURDATE() 
              ORDER BY s.sale_date DESC";
    $stmt = $db->prepare($query);
    $stmt->execute();
} else {
    // Employee sees only their sales
    $query = "SELECT s.*, :full_name as seller_name 
              FROM sales s 
              WHERE DATE(s.sale_date) = CURDATE() AND s.sold_by = :user_id
              ORDER BY s.sale_date DESC";
    $stmt = $db->prepare($query);
    $stmt->bindParam(':user_id', $user_id);
    $stmt->bindValue(':full_name', $_SESSION['full_name']);
    $stmt->execute();
}

$today_sales = $stmt->fetchAll();

// Calculate Payment Method Summary
$payment_summary = [];
$total_revenue = 0;

foreach ($today_sales as $sale) {
    $method = ucfirst($sale['payment_method']);
    if (!isset($payment_summary[$method])) {
        $payment_summary[$method] = 0;
    }
    $payment_summary[$method] += $sale['sale_price'];
    $total_revenue += $sale['sale_price'];
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Daily Sales Report</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        h1 { margin: 0; color: #333; }
        .meta-info { margin: 5px 0; color: #555; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        
        .total-row td { border-top: 2px solid #333; font-weight: bold; }
        .amount { text-align: right; }
        
        .summary-section { break-inside: avoid; display: flex; gap: 20px; margin-top: 20px; }
        .summary-box { flex: 1; border: 1px solid #ddd; padding: 15px; border-radius: 4px; }
        .summary-box h3 { margin-top: 0; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        .summary-list { list-style: none; padding: 0; margin: 0; }
        .summary-list li { display: flex; justify-content: space-between; margin-bottom: 5px; }
        
        @media print {
            body { padding: 0; }
            .no-print { display: none; }
            th { background-color: #eee !important; -webkit-print-color-adjust: exact; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center;">
        <a href="<?php echo $role === 'admin' ? 'admin.php' : 'employee.php'; ?>" style="padding: 10px 20px; background-color: #6c757d; color: white; text-decoration: none; border-radius: 4px;">&larr; Back to Dashboard</a>
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer; background-color: #007bff; color: white; border: none; border-radius: 4px;">Print Report</button>
    </div>

    <div class="header">
        <h1>Daily Sales Report</h1>
        <p class="meta-info">Date: <?php echo date('F j, Y'); ?></p>
        <p class="meta-info">Generated By: <?php echo htmlspecialchars($_SESSION['full_name']); ?> (<?php echo ucfirst($role); ?>)</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Time</th>
                <th>Item</th>
                <th>Type</th>
                <th>Customer</th>
                <?php if ($role === 'admin'): ?>
                <th>Seller</th>
                <?php endif; ?>
                <th>Method</th>
                <th class="amount">Price</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($today_sales) > 0): ?>
                <?php foreach($today_sales as $sale): ?>
                <tr>
                    <td><?php echo date('H:i', strtotime($sale['sale_date'])); ?></td>
                    <td>
                        <?php echo "Item #" . $sale['item_id']; ?>
                        <?php if(!empty($sale['notes'])): ?>
                            <br><small style="color: #666; font-style: italic;"><?php echo htmlspecialchars($sale['notes']); ?></small>
                        <?php endif; ?>
                    </td>
                    <td><?php echo ucfirst($sale['item_type']); ?></td>
                    <td>
                        <?php echo htmlspecialchars($sale['customer_name'] ?: 'N/A'); ?>
                        <?php if($sale['customer_phone']) echo "<br><small>" . htmlspecialchars($sale['customer_phone']) . "</small>"; ?>
                    </td>
                    <?php if ($role === 'admin'): ?>
                    <td><?php echo htmlspecialchars($sale['seller_name']); ?></td>
                    <?php endif; ?>
                    <td><?php echo ucfirst($sale['payment_method']); ?></td>
                    <td class="amount">XAF <?php echo number_format($sale['sale_price'], 0); ?></td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="<?php echo ($role === 'admin') ? 7 : 6; ?>" style="text-align: center; padding: 20px;">No sales found for today.</td>
                </tr>
            <?php endif; ?>
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="<?php echo ($role === 'admin') ? 6 : 5; ?>" style="text-align: right;">Total Daily Revenue</td>
                <td class="amount">XAF <?php echo number_format($total_revenue, 0); ?></td>
            </tr>
        </tfoot>
    </table>
    
    <div class="summary-section">
        <div class="summary-box">
            <h3>Payment Summary</h3>
            <ul class="summary-list">
                <?php foreach($payment_summary as $method => $amount): ?>
                <li>
                    <span><?php echo $method; ?>:</span>
                    <span>XAF <?php echo number_format($amount, 0); ?></span>
                </li>
                <?php endforeach; ?>
                <li style="border-top: 1px solid #ddd; margin-top: 5px; padding-top: 5px; font-weight: bold;">
                    <span>Total:</span>
                    <span>XAF <?php echo number_format($total_revenue, 0); ?></span>
                </li>
            </ul>
        </div>
        
        <div class="summary-box">
            <h3>Report Details</h3>
            <p><strong>Total Transactions:</strong> <?php echo count($today_sales); ?></p>
            <p><strong>Printed On:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>
        </div>
    </div>
    
    <script>
        // Auto-print only if not manually opened? Let's just focus input.
        // window.onload = function() { window.print(); }
    </script>
</body>
</html>